### PR TITLE
Added responsive navbar

### PR DESCRIPTION
**Pull request by sbdh11**

### CODE REVIEW

**Comment by yash37158** [comment]
is this responsive? can you also share the mobile view @DeltaCoderr

**Comment by yash37158** [comment]
@DeltaCoderr Also can you please change rules & naviagtion to code of conduct

**Comment by sbdh11** [comment]
> is this responsive? can you also share the mobile view @DeltaCoderr

Untitled

**Review by yash37158 — COMMENTED** [review]
can we have a more appealing hamburger icon ? @DeltaCoderr  maybe a light hamburger and with less border width will work

**Comment by sbdh11** [comment]
> can we have a more appealing hamburger icon ? @DeltaCoderr maybe a light hamburger and with less border width will work

Yeah, I couldn't find a good one so I just used this basic one for now. We can change the icon later once we find a decent one

**Comment by yash37158** [comment]
hey @DeltaCoderr, can you please integrate the recent changes

**Comment by sbdh11** [comment]
> hey @DeltaCoderr, can you please integrate the recent changes

Done!

**Pull request merged**
